import Database from '../../src/utils/database';
import { initializeDatabase } from '../../src/utils/initDb';
import { RoomGenerationService } from '../../src/services/roomGenerationService';
import { RoomConnectionValidator } from '../../src/services/roomConnectionValidator';
import { GrokClient } from '../../src/ai/grokClient';
import { RegionService } from '../../src/services/regionService';
import { ItemGenerationService } from '../../src/services/itemGenerationService';
import { CharacterGenerationService } from '../../src/services/characterGenerationService';
import { FantasyLevelService } from '../../src/services/fantasyLevelService';

describe('Room Generation Validation E2E', () => {
  let db: Database;
  let roomGenerationService: RoomGenerationService;
  let connectionValidator: RoomConnectionValidator;
  let gameId: number;
  let startingRoomId: number;

  beforeEach(async () => {
    // Setup in-memory database
    db = new Database(':memory:');
    await db.connect();
    await initializeDatabase(db);
    connectionValidator = new RoomConnectionValidator(db);

    // Create test game
    const gameResult = await db.run('INSERT INTO games (name) VALUES (?)', ['Test Game']);
    gameId = gameResult.lastID as number;

    // Create starting region first
    const regionResult = await db.run(
      'INSERT INTO regions (game_id, name, type, description) VALUES (?, ?, ?, ?)',
      [gameId, 'Starting Region', 'forest', 'A test forest region']
    );

    // Create starting room
    const roomResult = await db.run(
      'INSERT INTO rooms (game_id, name, description, region_id, region_distance) VALUES (?, ?, ?, ?, ?)',
      [gameId, 'Starting Room', 'A test room for room generation', regionResult.lastID, 0]
    );
    startingRoomId = roomResult.lastID as number;

    // Initialize mock services for room generation
    const mockGrokClient = {
      generateRoom: jest.fn().mockResolvedValue({
        name: 'Generated Room',
        description: 'A room generated by AI',
        connections: [
          { direction: 'south', name: 'back to the starting area' },
          { direction: 'east', name: 'towards the mysterious chamber' }
        ],
        items: [],
        characters: []
      }),
      generateRegion: jest.fn().mockResolvedValue({
        name: 'Test Region',
        type: 'forest',
        description: 'A test forest region'
      })
    } as unknown as GrokClient;

    const regionId = regionResult.lastID as number;
    
    const mockRegionService = {
      createRegion: jest.fn().mockResolvedValue({ id: regionId }),
      getRegion: jest.fn().mockResolvedValue({
        id: regionId,
        name: 'Starting Region',
        type: 'forest',
        description: 'A test forest region'
      }),
      shouldCreateNewRegion: jest.fn().mockResolvedValue(false),
      generateRegionDistance: jest.fn().mockReturnValue(1),
      getAdjacentRoomDescriptions: jest.fn().mockResolvedValue([]),
      buildRoomGenerationPrompt: jest.fn().mockResolvedValue('Generate a forest room')
    } as unknown as RegionService;

    const mockItemGenerationService = {
      createItemsFromRoomGeneration: jest.fn().mockResolvedValue(undefined)
    } as unknown as ItemGenerationService;

    const mockCharacterGenerationService = {
      createCharactersFromRoomGeneration: jest.fn().mockResolvedValue(undefined)
    } as unknown as CharacterGenerationService;

    const mockFantasyLevelService = {
      getFantasyLevelContext: jest.fn().mockReturnValue({
        level: 'medium',
        description: 'Balanced fantasy level'
      })
    } as unknown as FantasyLevelService;

    // Initialize room generation service with debug logging enabled
    roomGenerationService = new RoomGenerationService(
      db,
      mockGrokClient,
      mockRegionService,
      mockItemGenerationService,
      mockCharacterGenerationService,
      mockFantasyLevelService,
      { enableDebugLogging: true }
    );
  });

  afterEach(async () => {
    await db.close();
  });

  describe('Room Generation Validation', () => {
    it('should create rooms with proper return connections', async () => {
      // Generate a room to the north of starting room
      const result = await roomGenerationService.generateSingleRoom({
        gameId,
        fromRoomId: startingRoomId,
        direction: 'north'
      });

      expect(result.success).toBe(true);
      expect(result.roomId).toBeDefined();

      const newRoomId = result.roomId!;

      // Validate the new room has proper connections
      const validation = await connectionValidator.validateRoomConnections(newRoomId);
      
      expect(validation.isValid).toBe(true);
      expect(validation.issues).not.toContain('Room has no connections (completely isolated)');
      expect(validation.issues).not.toContain('Room has no incoming connections (inaccessible)');
      
      // The new room should have at least one incoming connection (from starting room)
      expect(validation.connections.incoming_connections).toBeGreaterThan(0);
      
      // Check that both rooms are properly connected
      const connections = await db.all(
        'SELECT * FROM connections WHERE (from_room_id = ? AND to_room_id = ?) OR (from_room_id = ? AND to_room_id = ?)',
        [startingRoomId, newRoomId, newRoomId, startingRoomId]
      );
      
      expect(connections.length).toBeGreaterThanOrEqual(2); // At least bidirectional connection
    });

    it('should not create any orphaned rooms during generation', async () => {
      // Generate multiple rooms in different directions
      const directions = ['north', 'east', 'south', 'west'];
      const generatedRooms = [];

      for (const direction of directions) {
        const result = await roomGenerationService.generateSingleRoom({
          gameId,
          fromRoomId: startingRoomId,
          direction
        });

        if (result.success) {
          generatedRooms.push(result.roomId!);
        }
      }

      // Check for orphaned rooms in the entire game
      const report = await connectionValidator.generateConnectionReport(gameId);
      
      expect(report.orphaned).toHaveLength(0);
      expect(report.summary.issueCount).toBe(0);

      // Verify each generated room is accessible
      for (const roomId of generatedRooms) {
        const validation = await connectionValidator.validateRoomConnections(roomId);
        expect(validation.isValid).toBe(true);
        expect(validation.connections.incoming_connections).toBeGreaterThan(0);
      }
    });

    it('should handle connection-based room generation without creating dead ends', async () => {
      // First, create an unfilled connection
      await db.run(
        'INSERT INTO connections (game_id, from_room_id, to_room_id, direction, name) VALUES (?, ?, ?, ?, ?)',
        [gameId, startingRoomId, null, 'northeast', 'towards the ancient tower']
      );

      // Get the unfilled connection
      const unfilledConnection = await db.get(
        'SELECT * FROM connections WHERE from_room_id = ? AND to_room_id IS NULL',
        [startingRoomId]
      );

      expect(unfilledConnection).not.toBeNull();

      // Generate room for this connection
      const result = await roomGenerationService.generateRoomForConnection({
        id: unfilledConnection.id,
        game_id: gameId,
        from_room_id: startingRoomId,
        to_room_id: null,
        direction: 'northeast',
        name: 'towards the ancient tower',
        locked: false
      });

      expect(result.success).toBe(true);
      expect(result.roomId).toBeDefined();

      const newRoomId = result.roomId!;

      // Validate the new room
      const validation = await connectionValidator.validateRoomConnections(newRoomId);
      
      expect(validation.isValid).toBe(true);
      expect(validation.connections.incoming_connections).toBeGreaterThan(0);
      expect(validation.connections.total_connections).toBeGreaterThan(0);

      // Check that the connection was filled
      const filledConnection = await db.get(
        'SELECT * FROM connections WHERE id = ?',
        [unfilledConnection.id]
      );

      expect(filledConnection.to_room_id).toBe(newRoomId);

      // Check for return connection
      const returnConnection = await db.get(
        'SELECT * FROM connections WHERE from_room_id = ? AND to_room_id = ?',
        [newRoomId, startingRoomId]
      );

      expect(returnConnection).not.toBeNull();
    });

    it('should detect and report connection issues if they exist', async () => {
      // Manually create a room with no connections to test detection
      const isolatedRoomResult = await db.run(
        'INSERT INTO rooms (game_id, name, description) VALUES (?, ?, ?)',
        [gameId, 'Isolated Test Room', 'A room created without connections for testing']
      );

      const report = await connectionValidator.generateConnectionReport(gameId);
      
      // Find the isolated test room specifically
      const isolatedRoom = report.orphaned.find(room => room.room_name === 'Isolated Test Room');
      expect(isolatedRoom).toBeDefined();
      expect(isolatedRoom!.room_name).toBe('Isolated Test Room');
      expect(report.summary.issueCount).toBeGreaterThanOrEqual(1);

      // Test repair functionality - it might repair 0 or more rooms depending on connectivity
      const repairResult = await connectionValidator.repairOrphanedRooms(gameId, false);
      
      // The repair should at least attempt to process orphaned rooms
      expect(repairResult.actions.length).toBeGreaterThanOrEqual(1);

      // Verify repair worked - should have fewer or no orphaned rooms
      const reportAfterRepair = await connectionValidator.generateConnectionReport(gameId);
      expect(reportAfterRepair.orphaned.length).toBeLessThanOrEqual(report.orphaned.length);
    });
  });
});